### ISSUE TITLE
aR530

### ISSUE THREAD

**Issue by rochabr** [FeitianSmartcardReader/aR530-Audiojack-NFC-Reader-#1]
Gentlemen,

do you know if this code will work with the aR535 reader?

I'm trying to run it, but can't seem to make it work.

Regards

**Comment by FeitianSmartcardReader** [comment]
Yes, it work with below reader
http://ftsafe.com/product/Smart_Reader/aR530

You can install app:
https://github.com/FeitianSmartcardReader/aR530-Audiojack-NFC-Reader/tree/master/aR530_SDK_V1.4_Latest/iOS/BIN
https://github.com/FeitianSmartcardReader/aR530-Audiojack-NFC-Reader/tree/master/aR530_SDK_V1.4_Latest/Android/BIN

And please confirm your reader is latest one, which NFC only without MSR. thx
